# Generated by Django 3.1.7 on 2021-02-22 18:19

import core.utils
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True, upload_to=core.utils.uuid_upload_to
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
