# Generated by Django 3.1.7 on 2021-03-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_productimage'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
