# Generated by Django 3.1.7 on 2021-02-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20210224_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SD", "개인판매"),
                    ("OP", "제품발주"),
                    ("SP", "입점처 입고"),
                    ("SS", "판매내역정산"),
                    ("LS", "입점처 퇴점"),
                    ("DS", "불량:입점처"),
                    ("DH", "불량:집"),
                ],
                max_length=2,
                verbose_name="재고 변화 타입",
            ),
        ),
    ]
