# Generated by Django 3.1.7 on 2021-03-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20210225_1833"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorychange", old_name="count", new_name="value",
        ),
    ]
