# Generated by Django 3.1.7 on 2021-03-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20210326_0255"),
        ("events", "0004_auto_20210326_0255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.store",
                verbose_name="입점처",
            ),
        ),
        migrations.AlterField(
            model_name="inventorychange",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_changes",
                to="events.event",
                verbose_name="재고 변화 내역",
            ),
        ),
        migrations.AlterField(
            model_name="inventorychange",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_changes",
                to="products.product",
                verbose_name="제품",
            ),
        ),
    ]
