# Generated by Django 3.1.7 on 2021-02-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="바코드"
                    ),
                ),
                ("description", models.TextField(verbose_name="설명")),
                ("price", models.PositiveIntegerField(verbose_name="가격")),
                (
                    "price_with_pees",
                    models.PositiveIntegerField(verbose_name="수수료포함 가격"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="보유 수량"
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        default=False, verbose_name="재입고 예정없음"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProductMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "image_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="제품 사진",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("core.image",),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                to="products.ProductCategory", verbose_name="카테고리"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="materials",
            field=models.ManyToManyField(
                to="products.ProductMaterial", verbose_name="재질"
            ),
        ),
    ]
