# Generated by Django 3.1.7 on 2021-02-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20210225_1833"),
        ("products", "0002_auto_20210225_1720"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField(verbose_name="재고 수량")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="제품",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.store",
                        verbose_name="입점처",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="storeproduct",
            constraint=models.UniqueConstraint(
                fields=("store", "product"), name="store-product"
            ),
        ),
    ]
