# Generated by Django 3.1.7 on 2021-03-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeproduct",
            name="count",
            field=models.PositiveIntegerField(verbose_name="재고 수량"),
        ),
    ]
