# Generated by Django 3.1.7 on 2021-03-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_auto_20210330_1645"),
        ("products", "0007_auto_20210326_0255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products",
                to="products.ProductCategory",
                verbose_name="카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="materials",
            field=models.ManyToManyField(
                related_name="products",
                to="products.ProductMaterial",
                verbose_name="재질",
            ),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_products",
                to="products.product",
                verbose_name="제품",
            ),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_products",
                to="events.store",
                verbose_name="입점처",
            ),
        ),
    ]
